### ISSUE TITLE
Getting error everytime I try to run the plugin

### ISSUE THREAD

**Issue by cybersecbalaji** [redcanaryco/vscode-attack#5]
I'm getting the following error whenever I try to run plugin in a Yaml file.

Command 'ATT&CK: Search ATT&CK Techniques' resulted in an error (command 'vscode-attack.search' not found)

**Comment by rctgardner** [comment]
That's not good. Do other features, such as the hover or code completion, work in that same file?

**Comment by cybersecbalaji** [comment]
-     Do other features, such as the hover or code completion, work in that same file?
Nope. 

-     Have you set any custom settings for the extension, and if so, what are they?
Nope, I have not modified the default setting.

-     Could you please share that YAML file or a representative sample so I can try to reproduce?
I was just testing it, attached it.  Please rename it as .yaml as github does not let me attached yaml files.
[test.txt](https://github.com/redcanaryco/vscode-attack/files/6333798/test.txt)



-     Could you please share the outputs of the "MITRE ATT&CK" channel, which can be found by clicking View > Output Channel and clicking in dropdown at the top right of the pane

This is what I can see,
![image](https://user-images.githubusercontent.com/53290305/115192667-747f4f00-a12e-11eb-9c80-9b274811ecbf.png)

**Comment by rctgardner** [comment]
It looks like the extension either hasn't downloaded or hasn't finished parsing the ATT&CK JSON mapping from the [mitre/cti](https://github.com/mitre/cti) GitHub repository. Do you have any trouble navigating to https://raw.githubusercontent.com/mitre/cti/ATT%26CK-v8.2/enterprise-attack/enterprise-attack.json or https://api.github.com/repos/mitre/cti/git/refs/tags ?

**Comment by cybersecbalaji** [comment]
I have tried uninstalling and reinstalling, still the same.

When you navigating, do you mean via any browser?

**Comment by rctgardner** [comment]
Yes, by browser. Do you have any security software that may be blocking connections from the editor to GitHub?

**Comment by cybersecbalaji** [comment]
I can by browser, but in VS Code somehow it's timing out when I try to ping. Somehow the DNS is looking for ipv6. I will do some research to see how I can fix it. 

![image](https://user-images.githubusercontent.com/53290305/115332258-cb426280-a1da-11eb-80c5-c1ad27ba5d30.png)

**Comment by rctgardner** [comment]
Interesting. Well, I'll be making some changes to the debug logging as a result of this anyway, and once you figure out what's happening I'd be interested in hearing how I can make this issue more obvious in the future. The output channel logs you posted didn't really do a good job of leading you to that, so that's definitely an area where we can improve.

**Comment by cybersecbalaji** [comment]
@rctgardner Thanks for your response. Yeah I have figured out the issue was because of my VPN. It is working fine in my home network. Sorry about that. Thank you developing this great extension.

**Comment by rctgardner** [comment]
Ah great to hear! I'll close this issue out, but please don't hesitate to open another one if need be
